name: citas_medicas
description: App de citas médicas
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.10.0'

dependencies:
  flutter:
    sdk: flutter

  # Iconos iOS
  cupertino_icons: ^1.0.8

  # Persistencia local
  shared_preferences: ^2.2.3

  # Notificaciones locales
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3

  # PDF
  pdf: ^3.11.0
  printing: ^5.13.0

  # Compartir archivos/texto
  share_plus: ^10.0.2
  path_provider: ^2.1.4

  # Calendario
  table_calendar: ^3.1.2

  # Abrir WhatsApp / mail / links
  url_launcher: ^6.3.0

  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_messaging: ^15.2.10

flutter:
  uses-material-design: true