// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlBXExdF1H5hf-T7bsjIVsnemIGb_CaGA',
    appId: '1:714645008730:web:6415f3e5619975594c0363',
    messagingSenderId: '714645008730',
    projectId: 'citas-medicas-64396',
    authDomain: 'citas-medicas-64396.firebaseapp.com',
    storageBucket: 'citas-medicas-64396.firebasestorage.app',
    measurementId: 'G-BNNZZNZBW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX7AHC1t_1fDW_PGGs6Y2zTVkgGnop9V0',
    appId: '1:714645008730:android:74bcd2ccd22e5a524c0363',
    messagingSenderId: '714645008730',
    projectId: 'citas-medicas-64396',
    storageBucket: 'citas-medicas-64396.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4LiJWkjs9mxZwAv0vj59e29rRlonRUEA',
    appId: '1:714645008730:ios:6ffaadc07a3bc45d4c0363',
    messagingSenderId: '714645008730',
    projectId: 'citas-medicas-64396',
    storageBucket: 'citas-medicas-64396.firebasestorage.app',
    iosBundleId: 'com.example.citasMedicas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4LiJWkjs9mxZwAv0vj59e29rRlonRUEA',
    appId: '1:714645008730:ios:6ffaadc07a3bc45d4c0363',
    messagingSenderId: '714645008730',
    projectId: 'citas-medicas-64396',
    storageBucket: 'citas-medicas-64396.firebasestorage.app',
    iosBundleId: 'com.example.citasMedicas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlBXExdF1H5hf-T7bsjIVsnemIGb_CaGA',
    appId: '1:714645008730:web:7e19c30d91acfcf44c0363',
    messagingSenderId: '714645008730',
    projectId: 'citas-medicas-64396',
    authDomain: 'citas-medicas-64396.firebaseapp.com',
    storageBucket: 'citas-medicas-64396.firebasestorage.app',
    measurementId: 'G-F8RYWK1G48',
  );

}